import classNames from "classnames";
import { ProjectTypes } from "./types";

// whenever wee need to change default className value we will use this
export const cx = classNames;

// nav data
export const navData = ["About", "Experiences", "Works", "Contact"];

// project data
export const projects: ProjectTypes[] = [
  {
    title: "Travello Booking",
    description:
      "Perfect for all kinds of travel agency. Including tours, hotel booking, activity/event, travel experiences, online booking, room bnb, villa rental, holiday rental, flight ticket, and more.",
    tech: [
      "Stripe",
      "Next.Js",
      "MongoDB",
      "Cloudinary",
      "React Icons",
      "Tailwind CSS",
      "React Leaflet",
      "Redux Toolkit",
      "React Hook Form",

      // "@reduxjs/toolkit",
      // "bcryptjs",
      // "autoprefixer",
      // "cloudinary",
      // "eslint",
      // "jsonwebtoken",
      // "eslint-config-next",
      // "mongoose",
      // "keen-slider",
      // "multer",
      // "leaflet",
      // "multer-storage-cloudinary",
      // "next",
      // "postcss",
      // "react",
      // "react-dom",
      // "react-hook-form",
      // "react-icons",
      // "react-leaflet",
      // "react-redux",
      // "tailwind-scrollbar-hide",
      // "tailwindcss",
      // "world-countries",
    ],
    github: "https://github.com/devhasibulislam/travello-template",
    youtube: "https://youtu.be/lUIinWktJW8?si=LWi3QSpC0f-r-FAX",
    live: "https://travello-template.vercel.app/",
    thumbnail: "travello-template.png",
    featured: true,
  },

  {
    title: "Canim eCommerce",
    description:
      "Shop seamlessly with top brands, secure transactions, swift deliveries, user-friendly navigation, and exclusive deals. Redefine convenience in our digital marketplace.",
    tech: [
      "@reduxjs/toolkit",
      "bcryptjs",
      "autoprefixer",
      "cloudinary",
      "eslint",
      "colors",
      "eslint-config-next",
      "cors",
      "next",
      "dotenv",
      "postcss",
      "express",
      "react",
      "jsonwebtoken",
      "react-dom",
      "mongoose",
      "react-icons",
      "multer",
      "react-redux",
      "multer-storage-cloudinary",
      "tailwind-scrollbar-hide",
      "validator",
      "tailwindcss",
      "nodemon",
      "@tailwindcss/forms",
    ],
    github: "https://github.com/devhasibulislam/canim-ecommerce",
    youtube: "https://youtu.be/0A_tPdRdkDw?si=TxAyapvf6u3C-JLm",
    live: "https://canim-csr.vercel.app",
    thumbnail: "canim-ecommerce.png",
    featured: false,
  },

  {
    title: "PlanNao EdTech",
    description:
      "All you need is mentor' is a pioneering ed-tech platform in Bangladesh connecting students with mentors for personalized guidance and bridging the gap between education and success.",
    tech: [
      "@reduxjs/toolkit",
      "autoprefixer",
      "bcryptjs",
      "cloudinary",
      "eslint",
      "eslint-config-next",
      "jsonwebtoken",
      "mongoose",
      "multer",
      "multer-storage-cloudinary",
      "next",
      "nodemailer",
      "postcss",
      "react",
      "react-dom",
      "react-hook-form",
      "react-redux",
      "sharp",
      "tailwindcss",
      "@tailwindcss/forms",
    ],
    github: "https://github.com/devhasibulislam/plannao-template",
    youtube: "https://youtu.be/lNbrDw0J6jc?si=sR-U5F3TROIwCE1Z",
    live: "https://plannao-template.vercel.app",
    thumbnail: "plannao-template.png",
    featured: false,
  },

  {
    title: "URL Shortener",
    description:
      "URL shortening is a technique on the World Wide Web in which a Uniform Resource Locator (URL) may be made substantially shorter and still direct to the required page.",
    tech: [
      "autoprefixer",
      "axios",
      "cheerio",
      "eslint",
      "eslint-config-next",
      "mongodb",
      "next",
      "postcss",
      "react",
      "react-dom",
      "tailwindcss",
    ],
    github: "https://github.com/devhasibulislam/lisonet-template",
    youtube: "https://youtu.be/5Hh2RwhlreY?si=Iws0PyljTz5iEiKP",
    live: "https://lisonet-template.vercel.app/",
    thumbnail: "url-shortener.png",
    featured: false,
  },
];
