import classNames from "classnames";
import { ProjectTypes } from "./types";

// whenever wee need to change default className value we will use this
export const cx = classNames;

// nav data
export const navData = ["About", "Experiences", "Works", "Contact"];

// project data
export const projects: ProjectTypes[] = [
  {
    title: "LaParis eCommerce",
    description:
      "Shop seamlessly with top brands, secure transactions, swift deliveries, user-friendly navigation, and exclusive deals. Redefine convenience in our digital marketplace.",
    tech: [
      "@reduxjs/toolkit",
      "bcryptjs",
      "autoprefixer",
      "cloudinary",
      "eslint",
      "colors",
      "eslint-config-next",
      "cors",
      "next",
      "dotenv",
      "postcss",
      "express",
      "react",
      "jsonwebtoken",
      "react-dom",
      "mongoose",
      "react-icons",
      "multer",
      "react-redux",
      "multer-storage-cloudinary",
      "tailwind-scrollbar-hide",
      "validator",
      "tailwindcss",
      "nodemon",
      "@tailwindcss/forms",
      "nodemailer",
      "react-hot-toast",
      "razorpay",
      "react-img-zoom",
      "react-select	",
      "swiper	",
      "yet-another-react-lightbox",
    ],
    code: "https://github.com/devhasibulislam/laparis-projectx",
    live: "https://laparis-projectx-csr.vercel.app",
    thumbnail: "laparis-template.png",
    featured: false,
  },

  {
    title: "Ciseco eCommerce",
    description:
      "Shop seamlessly with top brands, secure transactions, swift deliveries, user-friendly navigation, and exclusive deals. Redefine convenience in our digital marketplace.",
    tech: [
      "@reduxjs/toolkit",
      "bcryptjs",
      "autoprefixer",
      "cloudinary",
      "eslint",
      "colors",
      "eslint-config-next",
      "cors",
      "next",
      "dotenv",
      "postcss",
      "express",
      "react",
      "jsonwebtoken",
      "react-dom",
      "mongoose",
      "react-icons",
      "multer",
      "react-redux",
      "multer-storage-cloudinary",
      "tailwind-scrollbar-hide",
      "validator",
      "tailwindcss",
      "nodemon",
      "@tailwindcss/forms",
    ],
    code: "https://github.com/devhasibulislam/ciseco-ecommerce",
    live: "https://ciseco-csr.vercel.app",
    thumbnail: "ciseco-ecommerce.png",
    featured: false,
  },

  {
    title: "Travello Booking",
    description:
      "Perfect for all kinds of travel agency. Including tours, hotel booking, activity/event, travel experiences, online booking, room bnb, villa rental, holiday rental, flight ticket, and more.",
    tech: [
      "@reduxjs/toolkit",
      "bcryptjs",
      "autoprefixer",
      "cloudinary",
      "eslint",
      "jsonwebtoken",
      "eslint-config-next",
      "mongoose",
      "keen-slider",
      "multer",
      "leaflet",
      "multer-storage-cloudinary",
      "next",
      "postcss",
      "react",
      "react-dom",
      "react-hook-form",
      "react-icons",
      "react-leaflet",
      "react-redux",
      "tailwind-scrollbar-hide",
      "tailwindcss",
      "world-countries",
    ],
    code: "https://github.com/devhasibulislam/travello-template",
    live: "https://travello-template.vercel.app/",
    thumbnail: "travello-template.png",
    featured: false,
  },

  {
    title: "PlanNao EdTech",
    description:
      "All you need is mentor' is a pioneering ed-tech platform in Bangladesh connecting students with mentors for personalized guidance and bridging the gap between education and success.",
    tech: [
      "@reduxjs/toolkit",
      "autoprefixer",
      "bcryptjs",
      "cloudinary",
      "eslint",
      "eslint-config-next",
      "jsonwebtoken",
      "mongoose",
      "multer",
      "multer-storage-cloudinary",
      "next",
      "nodemailer",
      "postcss",
      "react",
      "react-dom",
      "react-hook-form",
      "react-redux",
      "sharp",
      "tailwindcss",
      "@tailwindcss/forms",
    ],
    code: "https://github.com/devhasibulislam/plannao-template",
    live: "https://plannao-template.vercel.app",
    thumbnail: "plannao-template.png",
    featured: false,
  },

  {
    title: "nLog Blogging",
    description:
      "Natural Way Of Blogging. By writing politically incorrect things uwu. Welcome to our cozy corner of the internet! A delightful mix of lighthearted musings, adventures, and insightful reflections.",
    tech: [
      "tailwind css",
      "nodemon",
      "@testing-library/jest-dom",
      "@hapi/joi",
      "@testing-library/react",
      "bcrypt",
      "@testing-library/user-event",
      "cookie-parser",
      "axios",
      "cors",
      "dayjs",
      "dotenv",
      "lodash",
      "express",
      "react",
      "express-paginate",
      "react-bottom-scroll-listener",
      "express-rate-limit",
      "react-dom",
      "jsonwebtoken",
      "react-router-dom",
      "mongo-sanitize",
      "react-scripts",
      "mongoose",
      "util",
      "morgan",
      "web-vitals",
      "nodemon",
    ],
    code: "https://github.com/devhasibulislam/nLog-blogs",
    live: "https://nlog-blogs-csr.vercel.app",
    thumbnail: "nLog.png",
    featured: false,
  },

  {
    title: "URL Shortener",
    description:
      "URL shortening is a technique on the World Wide Web in which a Uniform Resource Locator (URL) may be made substantially shorter and still direct to the required page.",
    tech: [
      "autoprefixer",
      "axios",
      "cheerio",
      "eslint",
      "eslint-config-next",
      "mongodb",
      "next",
      "postcss",
      "react",
      "react-dom",
      "tailwindcss",
    ],
    code: "https://github.com/devhasibulislam/lisonet-template",
    live: "https://lisonet-template.vercel.app/",
    thumbnail: "url-shortener.png",
    featured: false,
  },
];
